#!/bin/sh

set -eux

. ragnar-lib && init

# Given a snapshots build URL, rebuild a specified kernel and re-publish image
# and kernel files based on board type.
test -n "${URL}" || (echo "Set URL and try again"; exit 1)
test -n "${LINUX_GIT_URL}" || (echo "Set LINUX_GIT_URL and try again"; exit 1)
test -n "${LINUX_GIT_REFERENCE}" || (echo "Set LINUX_GIT_REFERENCE and try again"; exit 1)
test -n "${LINUX_GIT_REV}" || (echo "Set LINUX_GIT_REV and try again"; exit 1)
#URL=http://snapshots.linaro.org/openembedded/lkft/morty/hikey/rpb/linux-mainline/816
#LINUX_GIT_URL=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
#LINUX_GIT_REFERENCE=/home/drue/src/linux/mainline
#LINUX_GIT_REV=v4.17-rc3
# May also want an arg to just use an existing tree instead (useful for bisect)


rekernel_rootfs

